name: Build image and push

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
            - name: Template Dockerfile
              run: python update.py
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: codesmithtech/overpass-api:latest
                platforms: linux/amd64,linux/arm64
